# 1. Base Image (Platform) 

#FROM <base_image_name>

#Working Directory
#WORK DIR 

# Copying/Moving the content to Work Dir


# Expose PORT if it is web application

#Specify the starting point (Entry point) or RUN Command


# Use an official OpenJDK runtime as a parent image
FROM openjdk:21-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Java source file into the container
COPY HelloWorld.java HelloWorld.java

# Compile the Java application
RUN javac HelloWorld.java

# Define the command to run the application when the container starts
CMD ["java", "HelloWorld"]


